services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-analytics
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8400:8400"
    volumes:
      - ./data:/data
