"""

Revision ID: 83242035c4f0
Revises: 
Create Date: 2026-08-16 18:28:30.225932
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83242035c4f0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_overviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('channel_title', sa.String(length=512), nullable=False),
    sa.Column('channel_url', sa.String(length=1024), nullable=False),
    sa.Column('uploader_id', sa.String(length=256), nullable=False),
    sa.Column('uploader_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('channel_follower_count', sa.Integer(), nullable=True),
    sa.Column('playlist_count', sa.Integer(), nullable=True),
    sa.Column('views_timeline', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_overviews_channel_id'), 'channel_overviews', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channel_overviews_id'), 'channel_overviews', ['id'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.create_index(op.f('ix_themes_name'), 'themes', ['name'], unique=True)
    op.create_table('retrieved_shorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('channel_title', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=False),
    sa.Column('webpage_url', sa.String(length=1024), nullable=False),
    sa.Column('views_timeline', sa.JSON(), nullable=False),
    sa.Column('likes_timeline', sa.JSON(), nullable=False),
    sa.Column('comments_timeline', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieved_shorts_channel_id'), 'retrieved_shorts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_retrieved_shorts_id'), 'retrieved_shorts', ['id'], unique=False)
    op.create_index(op.f('ix_retrieved_shorts_video_id'), 'retrieved_shorts', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieved_shorts_video_id'), table_name='retrieved_shorts')
    op.drop_index(op.f('ix_retrieved_shorts_id'), table_name='retrieved_shorts')
    op.drop_index(op.f('ix_retrieved_shorts_channel_id'), table_name='retrieved_shorts')
    op.drop_table('retrieved_shorts')
    op.drop_index(op.f('ix_themes_name'), table_name='themes')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_channel_overviews_id'), table_name='channel_overviews')
    op.drop_index(op.f('ix_channel_overviews_channel_id'), table_name='channel_overviews')
    op.drop_table('channel_overviews')
    # ### end Alembic commands ###
